terra-money/assets

cw20/pairs.json
cw20/tokens.json

* due to distribution problem, we decided to redeploy testnet token / contracts

fix(cw20): redeploy testnet $MINE

---

cw20/pairs.json
cw20/tokens.json

https://spec.finance/ - Yield Optimizer on Terra Ecosystem
which is to be launched in mainnet soon

whitelist spectrum token mainnet and testnet

---

validators.json

Validator: terravaloper1d3fv2cjukt0e6lrzd8d857jatlkht7wcp85zar
Email: lunarcitizens@protonmail.com

Added Cives lunares

---

cw20/contracts.json

mAMD, mDOT, mSQ 
LP, Pair address

Add tokens contract address

---

cw20/pairs.json
cw20/tokens.json

change token address from `terra1zsruhx2yuv9548nn9lups2z99sqveg6e6upuse` to `terra1lqm5tutr5xcw9d5vc4457exa3ghd4sr9mzwdex`

feat(cw20): correct testnet MINE address

---

cw20/contracts.json
cw20/pairs.json

Add Spectrum Protocol to pairs.json for swap in Terra Station, and contracts.json for Terra Finder contract label.

add spectrum protocol to contracts.json and pairs.json

---

cw20/contracts.json

Please also add our (StarTerra) LP and Pair addresses

STT-UST Pair & LP

---

cw20/contracts.json

This PR included addresses of:
- [Airdrop Genesis](https://finder.terra.money/columbus-5/address/terra1q2qprmuva3m93vhjmc7vakhs0h2lelxzlt675p)
- [Signing](https://finder.terra.money/columbus-5/address/terra1mz8qcfplg3s46zkkj9jywmguehpenhahcqc22q)
- [KYC Vault](https://finder.terra.money/columbus-5/address/terra1ru8qeh0mvf8m80vul84wsljqvltm6t64n8gjr0)

Additional StarTerra contracts

---

cw20/pairs.json
cw20/tokens.json

Please do not merge PR before confirmation from the team

Added ORION/UST Pair

---

cw20/contracts.json
cw20/pairs.json
cw20/tokens.json

This PR adds Terraland mainnet assets to terra-money.

Terraland assets

---

cw20/contracts.json

Adds 1 token, WHALE token on testnet.
icon is taken from github org logo at 100x100 size.

feat(whale-token): Add testnet whale token.

---

cw20/contracts.json
cw20/pairs.json
cw20/tokens.json

Pull request adds the info on Lido wstETH token bridged through Wormhole to Terra

Add wstETH token + terraswap pair info

---

cw20/contracts.json
cw20/pairs.json
cw20/tokens.json

Pull request adds the info on Lido stSOL token bridged through Wormhole to Terra

Add stSOL token + terraswap pair info

---

cw20/contracts.json
cw20/pairs.json

Few more labels for relevant vesting, staking & multisig addresses

Kuji contract addresses

---

cw20/contracts.json

New contracts from StarTerra:
- Vesting Advisors
- Vesting Team
- Governance

New StarTerra contracts addresses

---

cw721/contracts.json

I've included the finalized URLs for our icons, but we will be updating the content of those URLs in the next few days with finalized images.

Add Levana Dragons (meteors, eggs, and dust)

---

cw20/tokens.json

Add Bitlocus Token to the list of tokens
Website: https://btl.bitlocus.com
Whitepaper: https://bitlocus.gitbook.io/bitlocus/bitlocus-solution

Add BTL token

---

cw20/tokens.json

Add LunaX Token to the list of tokens

Add lunax Token

---

cw721/contracts.json

feat: xyz cw721 asset

---

cw721/contracts.json

https://twitter.com/BestGirlsNFT
https://knowhere.art/collection/terra1cdd4k8shstdsrfl83c2f2hts8kfh636k58uqmm

Add Terra Best Girls to the Whitelist

---

cw721/contracts.json

Add main net and testnet contracts for RESToads.
Mainnet marketplace:
https://randomearth.io/collections/terra1lt4e5r5rhddhercgpk6v567z2yd3ucxq5n8jsh

feat: add rest-nft

---

cw20/tokens.json

Pair + Contract info will be applied soon

feat(cw20): register bPsiDP

---

cw20/contracts.json
cw20/tokens.json

Splitting of https://github.com/terra-money/assets/pull/116

feat(tokens): register Orne token

---

cw721/contracts.json

TerraPeeps

---

cw721/contracts.json

Added the info for Poppin Puffins to the whitelist file.

Added Poppin Puffins to contracts.json

---

cw20/pairs.json

Splitting of https://github.com/terra-money/assets/pull/116

feat(pairs): register Orne/UST pair

---

cw721/contracts.json

NFT Team of Luna Punks.
https://lunapunks.io
https://twitter.com/LunaPunksNFT

Add LunaPunks mainnet contract

---

cw721/contracts.json

ADD deviants factions starter packs.

Deviants factions starter packs

---

cw721/contracts.json

Update collections - Add Unstables

---

cw721/contracts.json

Hi, it's TZM from the LunaBulls team. 
I added our details to be listed on the Terra Station.
Cheers.

Added LunaBulls entry

---

cw721/contracts.json

Add Luna Meow contract information

Add Luna Meow contract information

---

cw721/contracts.json

Add in TerraGems collection of NFT from knowhere in order to add to Terra Station. Thank you.

Update Json - TerraGems Collection

---

cw20/contracts.js
cw20/tokens.js
cw721/contracts.js

Co-Authored-By: TerraFloki <91100505+TerraFloki@users.noreply.github.com>
Since I moved the lists to JavaScript in #147, I felt that I should help out and convert this pull request over.

feat: Add TerraFloki essential contracts.

---

cw20/tokens.js

added bridged lido dao token (wormhole)
original token - https://etherscan.io/token/0x5a98fcbea516cf06857215779fd812ca3bef1b32
wormhole terra token - https://finder.terra.money/mainnet/address/terra1jxypgnfa07j6w92wazzyskhreq2ey2a5crgt6z

added lido dao token (wormhole) info

---

cw20/tokens.js

Adding Noks token to tokens.js

---

cw20/tokens.js

Added Lido staked Luna token — stLuna.
More info about it: 
https://blog.lido.fi/stluna-the-next-generation-of-liquid-staking-on-terra/
https://lidofinance.github.io/terra-docs/introduction/deployed-contracts

Adding stLuna token 

---

cw721/contracts.js

Fixed icon link to include `https://`

Updated icon protocol to https

---

cw721/contracts.js

All details are updated in contracts.js file

Adding Luna Monkey Business to Terra Station

---

cw20/contracts.js
cw20/pairs.js
cw20/tokens.js
cw721/contracts.js

- Add multiple TNS contract addresses
- Add TNS-UST pair address
- Add TNS token address
- Add TNS NFT address

Add TNS assets

---

cw20/contracts.js
cw20/tokens.js

- Move TNS token from testnet to mainnet
- Add Collector contract address

Move TNS token to mainnet, Add collector contract

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

Let me know if anything else need to be done ;)

Add Thorstarter's Token & Contracts

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

Hey there! 👋🏻 
This PR add the Orne token to the testnet.
Let me know if you need anything else.

feat: add Orne Token & Pair to testnet

---

cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

Add $SITY pool, cw20 and pair info

CW20 Update listing Curio $SITY token

---

extensions.json

Added leap wallet extension metadata

feat. add leap wallet to extensions whitelist

---

cw721/marketplace.js

CW721 Update adding Curio NFT marketplace.js 

---

cw20/tokens.js

Project info: https://apollo.farm/

Add APOLLO to CW20 tokens

---

cw20/tokens.js

Adds Wormhole version of the bETH token to testnet.

Add Wormhole bETH token to testnet

---

cw721/contracts.js

To add MinervaDAO's governance NFTs

Update contract.js for Minerva

---

cw20/tokens.js

Have added SHARD token for GlassFinance in terra testnet.

Add shard token in testnet

---

cw20/pairs.js

Have added UST-SHARD pair to terra testnet

Add UST-SHARD Pair to testnet

---

cw20/pairs.dex.js

Have added UST-SHARD terraswap to testnet.

Add UST-SHARD swap to terra testnet

---

cw20/tokens.js

adding Proteus Token in the testnet list

Update token.js for Proteus Token

---

cw20/tokens.js

Added the cw20 token for Prism Protocol (PRISM)

Add PRISM token

---

cw20/tokens.js

Update token.js for address and logo update on Testnet

address and logo update testnet - Proteus

---

cw721/contracts.js

I added new collection - Unstables: Guardians of Terra to the file
I deleted duplicate (there was 2x the same record in the file)

Unstables Terra - Guardians Contract Added

---

cw20/tokens.js

Governance token for Prism Protocol.

Add xPRISM cw20 token

---

cw721/contracts.js

Added:
- LunaBulls 3D
- LunaBulls Tesseracts
- BabyBulls
Updated marketplace and icon links.

Updated LunaBulls entries

---

cw20/pairs.js

Added Loop and Loopr pair, updated pair.js

---

cw20/tokens.js

[C2X] Added C2X Token

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

+ Added vUST to contracts.js
+ Added WHALE/UST address to pairs.dex.js
+ Added trading pair to pairs.js
+ Added vUST to tokens.js
Will mark as ready once we have the vust logo serving on our website! Feel free to leave any comments in the mean time.

feat(whale): Add vUST logo and update whale details

---

cw20/tokens.js

adding first attempt for cw20 token

adding first attempt for cw20 token

---

cw20/contracts.js
cw20/tokens.js

* Adds $ATLO token address
* Adds contract addresses for: Treasury, Fees, Vesting, Staking, LP, Voting and Governance
Modifies:
1. `cw20/contracts.js`
2. `cw20/tokens.js`

Adds Atlo details

---

cw721/contracts.js

Details updated within contracts.js

Added TerraSkulls to Terra Station

---

cw721/contracts.js

The project contract has been changed to terra1dh4tjp2qt8axyvp354hevdvv940dcecqd3f4nh

Update Contract of Terra Best Girls

---

cw721/contracts.js

GoFund US(T) NFT

---

cw20/contracts.js
cw20/tokens.js

Adds the pool ad bonded token address for protocol revenue as per [vote#3](https://blue.kujira.app/govern/3)

Add sKUJI pool & token

---

cw20/tokens.js

Luv token add

---

cw20/pairs.js

LUV/UST pair added to pairs.js

---

cw721/contracts.js

GoFund US(T) NFT (mainnet&testnet)

---

cw721/marketplace.js

{
name: "Messier Art",
link: "https://messier.art",
icon: "https://assets.messier.art/logo.png",
}
Thanks team

Update messier.art marketplace

---

blacklist.json

Remove duplicate anchorprotocoi.com (another is at line 68)

Duplicate with line 68 anchorprotocoi.com

---

cw20/tokens.js

Add CW20 Token

---

cw20/pairs.js
cw20/tokens.js

Hi! could I please add MintDAO assets?
terra1zd6let0zg0xjn2sestagxv4ax24a4ml6j40qdr - mint token address mainnet
terra1fdwsevq7skhfq93zkg0xxr6zrv29aqupw2fura - pair address mainnet
terra19tn6v77xf2v5tkd0g3dl5wqvjdh8d0u4g3p2j7 - lp token address mainent
Liquidity will be added on Monday 12:00 UTC

Add MintDAO assets

---

cw20/tokens.js

Fix https://github.com/terra-money/assets/pull/348, move PAXG to mainnet

fix: move PAXG to mainnet

---

cw20/tokens.js

The bATOM contract has been changed on Testnet

updated bATOM contract addr on testnet

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

Add sayve token, pair and lp contracts

Add Sayve 

---

cw20/tokens.js

Signed-off-by: WildCommunist <alex@ceres.ventures>

Update cvUST testnet image

---

cw20/pairs.js

add pair CTX-LCT

---

cw20/tokens.js

update PROTEUS token

---

cw20/tokens.js

mainnet : add LCT
testnet : add CST

add LCT CST

---

cw721/contracts.js

Add Astroport Lockdrop NFT's. Source - https://twitter.com/astroport_fi/status/1511449476787019783.

Add Astroport Lockdrop NFT's

---

cw20/tokens.js

Update bATOM and webATOM terra contracts for mainnet.

bATOM anchor mainnet update

---

blacklist.json

phishing Terra Station pop-up at page stationterra.xyz/terra/node/Terra.html

added stationterra.xyz to blacklist

---

cw721/contracts.js

Add Knowhere Art's marketplace to the Astroport Lockdrop NFT.

Add marketplace for Astroport Lockdrop NFT

---

cw20/pairs.js

mainnet : add pair LCT-CTX

---

cw20/tokens.js

mainnet : add token LCTfancard

mainnet : add token LCTfancard

---

cw20/tokens.js

mainnet : [fix] LCTfancard decimals

mainnet : [fix] LCTfancard decimals

---

cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

Outp0st demo token, pair dex added. Thanks in advance!

Testnet outp0st demo

---

cw20/tokens.js

Adding KNTC and kUST tokens from Kinetic Money. Also removed extra spacing of previous entry.

Adding KNTC and kUST tokens.

---

cw20/contracts.js
cw20/tokens.js

Add Steak contracts

---

cw20/contracts.js

add Nexus autocompounder & bATOM vault & wasAVAX vault contract addresses

new Nexus protocol contracts

---

cw20/pairs.dex.js
cw20/pairs.js
cw20/tokens.js

mainnet: add token CST, CSTfancard
thank you

mainnet: add token CST, CSTfancard

---

cw20/tokens.js

add token SB

---

cw20/pairs.js

add Pair uusd - DragonSB

---

cw20/tokens.js

https://twitter.com/orion_money/status/1519774709067440129
https://orion-money.medium.com/announcing-astrobooster-d6e183cf1b67

Add orionASTRO Token

---

cw20/tokens.js

Pavo finance token info updates

---

blacklist.json

Adding scam site terra-bridge.money

Adding scam site terra-bridge.money

---

cw20/pairs.dex.js

Listing PAVO-UST Pair to DEX

---

cw20/tokens.js

Adding the bSOL collateral token to mainnet

adding bSOL collateral token

---

chains.json

We are retiring Bombay testnet.

Remove bombay testnet

---

cw20/pairs.dex.js
cw20/tokens.js

- tokens
- BST
- KRX
- BSTfancard
- KRXfancard
- pairs
- BST-CTX
- KRX-CTX

feat: add BST, KRX to classic whitelist

---

cw20/pairs.dex.js

new pairs: LUNA-USDT, LUNA-USDC, USDC-USDT

add new Terraswap pairs

---

ibc/tokens.js

Revised a typo

---

cw20/tokens.js

These are legit Astroport tokens from the Astroport medium and can be verified here - https://astroport.medium.com/astroport-activates-staking-on-terra-2-0-1f298e4cb22d.

Add legit Astroport tokens (previous pull was denied so source is also provided).

---

cw20/tokens.js

- fix BSTfancard, KRXfancard decimals to 0
- add ILT, ILTfancard tokens to classic whitelist

feat: update classic whitelist

---

cw20/pairs.dex.js

feat: add ILT-CTX pair to classic whitelist

---

ibc/tokens.js

Added axlETH to testnet configuration

added axlETH to Testnet

---

cw20/tokens.js

forgot this file.
Sorry about the double up

Add Gido Token

---

cw20/tokens.js

* SD Token (phoenix-1)
* Mainnet Contract > https://finder.terra.money/mainnet/address/terra1l23rtnsp0fcfgs2zlww4gcd8dlznkm580p5yrsangcen9jjjhuqstd2sle
Protocol: Stader
https://twitter.com/staderlabs

Add SD token

---

cw20/tokens.js

* Add SD Token (phoenix-1)
* Remove  SD Token (classic)
* Mainnet Contract > https://finder.terra.money/mainnet/address/terra1l23rtnsp0fcfgs2zlww4gcd8dlznkm580p5yrsangcen9jjjhuqstd2sle
Protocol: Stader
https://twitter.com/staderlabs

Add SD token terra 2.0

---

cw20/tokens.js

* RED Token (phoenix-1)
* Mainnet Contract > terra1xe8umegahlqphtpvjsuwfzfvyjfvag5h8rffsx6ezm0el4xzsf8s7uzezk
* Protocol: Redacted.Money
* https://twitter.com/redacted_money

Add RED Token

---

cw20/pairs.dex.js

@octalmage  / @Jared-TFL
Updated  superscripts in Mainnet section
from ”astroport”
to "astroport"
update it accordingly if you believe it's relevant.
Regards,
Emanuele
https://lira.financial

Changed  superscripts ”” to "" in Mainnet

---

cw721/contracts.js

Add Ronin NFT by RedactedMoney 
Contract: terra1hh9rgaxtmfqfkeqkruckwah6qc4ajlxgnweexyjeh4dsptkfnhmqeelzfl
Marketplace: https://knowhere.art/collections/terra1hh9rgaxtmfqfkeqkruckwah6qc4ajlxgnweexyjeh4dsptkfnhmqeelzfl

Add Ronin NFT

---

cw721/contracts.js

Add Luna Ape Club NFT

---

cw721/contracts.js

- Add LunaBurningKnights NFT contract to classic
- update lunapunks classic webpage

Add LunaBurningKnights NFT contract to classic

---

cw20/pairs.dex.js

- change terraswap dex pair list on classic network to support lunc tax

fix: change terraswap dex list to support tax

---

cw20/contracts.js

- change terraswap-related contract addresses to support tax

fix: change terraswap contract addresses

---

cw20/tokens.js

Add Terra Poker Token
https://terra.poker

Add Terra Poker Token

---

cw721/contracts.js

Added TerraBots mainnet contract.

Update contracts.js. Added TerraBots contract.

---

cw20/tokens.js

This PR adds ampLunc to the classic token list.

added ampLunc to classic

---

cw20/pairs.dex.js
cw20/tokens.js

Reverts terra-money/assets#635

Revert "Add 2 assets 1) OPZC and 2) OPZA for optimizer project."

---

station/chains.js

Reverts terra-money/assets#688

Add Mars back

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/tokens.js
cw721/contracts.js

Hi! Just added token image for dUST ( Depegged UST) and two collections ( Depeg Nation & Depeg Nation: Tales of dUST) thank you!

Depeg Nation PR

---

cw20/pairs.dex.js
cw20/tokens.js

Add Moon Dust token and trading pair

Add Moon Dust Token

---

cw20/tokens.js

Fix ampLUNA-T address

---

cw20/contracts.js
cw20/tokens.js

This PR renames the WHALE token to WHALEC on Terra Classic.

refactor: rename terra classic WHALE token to WHALEC

---

cw20/contracts.js
cw20/pairs.dex.js
cw20/tokens.js

Added Sayve token
terra1xp9hrhthzddnl7j5du83gqqr4wmdjm5t0guzg9jp6jwrtpukwfjsjgy4f3
Added xSayve token
terra16zc783wt2w5lvlt9u4as977lt39c3se427akkenrzyax5vtde70qa89ukv
Added Sayve-Luna Pair token for astroport
terra1nckl6ex6239tv4kjzv03ecmuxwakjm8uj8cy6p850vmlmejfmj9sy094yr
Renamed SAYVE on Classic to SAYVEC

Added Sayve token

---

cw20/contracts.js
cw20/tokens.js

Added LBUN token, contract terra1ulr678u52qwt27dsgxrftthq20a8v8t9s8f3hz5z8s62wsu6rslqyezul4. LBUNswap dApp is at: https://lbunswap.netlify.app/

Added LBUN Token

---

cw20/contracts.js

Sonic(k) is a Social that involves many interactions with the outside world. By connecting they interconnect and interact with news, links, entertainment games but above all digital NFTs that can be exchanged and collected as if they were a simple image. Sonic platform will be constantly updated to implement new features. $SON is the governance token

New Smart contract Sonic Token added

---

cw20/pairs.dex.js
cw20/tokens.js

used last pull request by TRUMP Dao and appended to it
token
terra1rc6ssp5rym7a0hg29xpj4cc9e67tl56kg5jyzgl9qrhfxxc2ugvsnrkala
pair
terra1rd707p4u6wl774typcmjk7ut9vjfswawss9kh6r94alx37fkn7ksw6kznf
LP token
terra1z2qxassg2h6zpq844uguj8d66df9t5ja9glxd55mv9xv5gp9j5dqeuhpx8

Added SEAS Token info and Pair

---

station/tfm.js

add ampkuji for tfm

---

cw20/tokens.js

Add DKW token

---

chains.json

TerraRebels / Haxxagon sunsetting api endpoint

chains.json update due to sunsetting api endpoint by TerraRebels

---

cw20/pairs.dex.js
cw20/tokens.js

whitelist DFC token, DFC-USTC pair and DFC-LUNC pair.

Add DFC Token to Terra Classic

---

cw20/pairs.dex.js
cw20/tokens.js

Dear TFL Team,
I humbly ask you to accept these config changes on your asset repository to list the Terra Classic Token LUNW. Thank you.
Best,
Till

Add LUNW Token and Pair

---

cw20/contracts.js
cw20/tokens.js

Added GarudaX token

---

cw20/contracts.js
cw20/tokens.js

Change old contracts with Terraport V2 contracts

upgrade Terraport contract

---

cw20/contracts.js
cw20/tokens.js

Added Tritium token
- Site (https://terratritium.com/)
- X (https://twitter.com/terratritium)

Added Tritium token

---

cw20/pairs.dex.js
cw20/tokens.js

added bmos

---

cw20/contracts.js
cw20/tokens.js

Add ITO token

---

cw20/tokens.js

Update tokens.js - Update ASTRO.cw20 and xASTRO.cw20

---

cw20/tokens.js

whitepaper available at T.me/TheUluruTribeARK

ARIKATOKEN.js
