terra-money/assets

chains.json
Walletconnect divides chainID into number. (This is because walletconnect is based on etherium)
Add the walletconnectID attribute to the chains.json to use the chains.json file for the walletconnect network classification that is currently hardcoded.
=> feat: Add walletconnectID to chains.json

cw20/pairs.json
Adding LunaX <=> Luna pair contract.
terra1zrzy688j8g6446jzd88vzjzqtywh6xavww92hy is the LP contract
terra17y9qkl8dfkeg4py7n0g5407emqnemc3yqk5rup is the cw20 token contract for LunaX
=> Add LunaX to pairs.json

cw20/tokens.js
Adds mainnet HALO CW20 Token to the `cw20/contracts.js` file.
=> Add HALO Token

cw20/tokens.js
The team Legends of Terra has opened the public sale of the alpha pack token (cw20). We want the token to be listed as a Terra asset. Thanks!
[https://playlot.io](https://playlot.io)
=> Add LoT Alpha Pack Token (cw20)

cw20/tokens.js
* Adds Wormhole version of the bETH token to mainnet.
* Fixes the name of the token on testnet to match the mainnet one.
=> Add Wormhole bETH token to mainnet

cw20/tokens.js
Change the Wormhole bETH token name to follow the Wormhole token naming convention used in Terra (the `we` prefix designates the Ethereum origin of the token).
=> Use conventional Wormhole bETH token name

cw20/tokens.js
Changed the whLDO symbol to weLDO so it would be compatible with calling convention for Ethereum assets bridged with Wormhole
=> Change whLDO to weLDO

cw20/tokens.js
Space Dollar token is used to gain access to Space Dollar Society, it's also used to farm tickets that are redeemable for NFTs
=> Add Sdollar token

contracts.json
Add TNS Reverse Record address, this address is used to resolve ".ust" name from a terra address.
E.g., Resolving `bucky.ust` from `terra1aaaaa...bbbbb`.
=> Add TNS Reverse Record Address

cw20/contracts.js, cw20/pairs.dex.js, cw20/pairs.js
Hey! 👋🏻 
We have migrated $ORNE to Astroport.
This PR removes the TerraSwap pair and registration to only use the Astroport one.
=> feat: migrate Orne to astroport

cw20/tokens.js
Reverts #106. The new Mars token was added in #306.
=> Remove old Mars token

cw20/tokens.js
Wrapped Token: https://finder.terra.money/columbus-5/address/terra1z3e2e4jpk4n0xzzwlkgcfvc95pc5ldq0xcny58
Token symbol: `wasAVAX`
=> Add Benqi sAVAX to mainnet tokenlist

cw20/tokens.js
This adds token metadata for Wormhole-wrapped test bSOL.
This is part of testing the Anchor integration of Lido for Solana, which will allow users of Anchor to use staked SOL as collateral. See also https://github.com/ChorusOne/solido/milestone/4.
This is one particular test for bSOL, we might redeploy the setup later and change the addresses, but for now we want to be able to use this deployment for testing.
Solana devnet token address: https://explorer.solana.com/address/BSo147oW1Nd2AmVKHCgEz9hGAQ9zZLqZWTAXp3p3gxPQ?cluster=devnet
Registration transaction: https://finder.terra.money/bombay-12/tx/615F21A519D5BF38D35789DF4D3F8CE1A67739B0D7738A03F50A6CA1F8FA0D79
Terra testnet token address: https://finder.terra.money/testnet/address/terra1spt8mjrg5w8er4na206x24gyrtvr278q78vpwa
The token on …
=> Add testnet Wormhole bSOL

cw20/tokens.js
This is a fix of Wormhole webAtom Token Contract used by Anchor and wormhole, the [contract](https://finder.terra.money/bombay-12/address/terra16ythupvqqkdwfvd2fdcxl7uzesqw9hv9h594q2) is initiated with 6 decimal places. This is an urgent requirement.
=> webAtom decimal changed

cw20/tokens.js
It's showing up as "undefined LINK Token" in the finder, so I guess the "protocol" property
is needed and "name" is ignored?
=> Fix up LINK token definition

cw20/tokens.js
Adds bSOL Anchor token to testnet.
- address: https://finder.terra.money/testnet/address/terra17ewm2qjljcvfpmsnje68fnf7tnxecw4prs84sx
- decimals: 6
=> feat: add bSOL anchor token to testnet

cw20/tokens.js
This PR adds the two tokens of the brokkr protocol (BROtocol) to the cw20 token.js.
Verify the info yourself:
BRO token:
https://finder.extraterrestrial.money/mainnet/address/terra1mt2ytlrxhvd5c4d4fshxxs3zcus3fkdmuv4mk2
bBRO token:
https://finder.extraterrestrial.money/mainnet/token/terra1qryq5wreecx2wd3cdtzz94syr4z0a92l60asds
brokkr website:
https://brokkr.finance/
=> add brotocol cw20 tokens

blacklist.json
they all host scam websites at "/en" route, so full urls would be 
* terramoneyservice.com/en
* terra-ecosystem.com/en
* terra-ecosystem.xyz/en
=> added more entries to blacklist

cw20/tokens.js
Adding xASTRO token to the mainnet list and also adding the decimal parameter to ASTRO token. Source of Token Address - https://astroport.medium.com/astroport-upgrade-unleashed-governance-staking-and-fee-share-8d17e4adb97c.
=> Add xASTRO token and add decimal parameter to ASTRO

blacklist.json
Add scam Astroport site to the blacklist - https://actroport-app.digital/.
=> Add scam Astroport site to the blacklist - https://actroport-app.digital/

cw20/tokens.js
`terra1c3xd5s2j3ejx2d94tvcjfkrdeu6rmz48ghzznj` is the Wormhole-wrapped version of bSOL on Solana (https://explorer.solana.com/address/EbMg3VYAE9Krhndw7FuogpHNcEPkXVhtXr7mGisdeaur/metadata).
I see the names are being changed in #393 from “(Wormhole)” to “(Portal)”, so I added it with “(Portal)” suffix already. I hope it doesn’t cause any more confusion.
=> Add mainnet Wormhole-wrapped bSOL

cw20/tokens.js
Added Nexus releated tokens (nLuna, nETH, cnLuna and cnETH) also added decimal parameter to PSI.
=> Added Nexus releated tokens.

cw20/tokens.js
Add Reactor Money RCT Token.
Source - https://twitter.com/reactor_money/status/1519528488969306113.
=> Add Reactor Money RCT Token

cw20/tokens.js
it currently points to the github file detail page instead, unlike every other icon URL in tokens.js
=> Replace PAXG icon url with link to actual image

extensions.json
Sorry about this. They deprecated the URL I just PR'd last time.
=> Update Leap Wallet logo URL

cw20/pairs.dex.js
Fix pairs.dex.js
```
testnet: {},
^
SyntaxError: Unexpected token ':'
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1049:15)
at Module._compile (node:internal/modules/cjs/loader:1084:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
at Module.load (node:internal/modules/cjs/loader:998:32)
at Module._load (node:internal/modules/cjs/loader:839:12)
at Module.require (node:internal/modules/cjs/loader:1022:19)
at require (node:internal/modules/cjs/helpers:102:18)
at /Users/thomaswos/git/terra/assets/index.js:15:20
at Array.forEach (<anonymous>)
```
=> Fix pairs.dex.js

station/chains.js
This pull request delete Mars Protocol LCD because the servers are down and I could not find another lcd instance.
If MarsProtocol is needed please revert this PR @alecande11
=> fix: app loading
